<?php

namespace Database\Seeders;

use App\Model\Question;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('questions')->insert([
            [
                'category_id' => '1',
                'question' => 'Who are all ________ people?',
                'correct_answer' => 'those',
                'incorrect1' => 'this',
                'incorrect2' => 'them',
                'incorrect3' => 'that',
                'status' => '0',
            ],
            [
                'category_id' => '1',
                'question' => 'Claude is ________',
                'correct_answer' => 'a French',
                'incorrect1' => 'Frenchman',
                'incorrect2' => 'a Frenchman',
                'incorrect3' => 'French man',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => ' I ____ a car next year.',
                'correct_answer' => 'am buying',
                'incorrect1' => 'buy',
                'incorrect2' => 'going to buy',
                'incorrect3' => 'bought',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'They are all ________ ready for the party',
                'correct_answer' => 'getting',
                'incorrect1' => 'going',
                'incorrect2' => 'doing',
                'incorrect3' => 'putting',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'When do you go ________ bed?',
                'correct_answer' => 'to',
                'incorrect1' => 'to the',
                'incorrect2' => 'in',
                'incorrect3' => 'in the',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'London is famous for _____ red buses.',
                'correct_answer' => '6',
                'incorrect1' => '9',
                'incorrect2' => '15',
                'incorrect3' => '20',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Is there _____ milk in the fridge?',
                'correct_answer' => 'some',
                'incorrect1' => 'a lot',
                'incorrect2' => 'many',
                'incorrect3' => 'much',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'There is a flower shop in front _____ my house.',
                'correct_answer' => 'of',
                'incorrect1' => 'to',
                'incorrect2' => 'off',
                'incorrect3' => 'in',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Where are _____ children? They go to school.',
                'correct_answer' => 'the',
                'incorrect1' => 'you',
                'incorrect2' => 'a',
                'incorrect3' => 'an',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Those students are working very _____ for their next exams.',
                'correct_answer' => 'hard',
                'incorrect1' => 'hardly',
                'incorrect2' => 'harder',
                'incorrect3' => 'hardest',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Jane _____ as a fashion designer becoming a famous singer.',
                'correct_answer' => 'worked',
                'incorrect1' => 'is working',
                'incorrect2' => 'works',
                'incorrect3' => 'will work',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Dan can _____ the drum very well.',
                'correct_answer' => 'play',
                'incorrect1' => 'do',
                'incorrect2' => 'make',
                'incorrect3' => 'think',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'I know somebody ________ can play the guitar.',
                'correct_answer' => 'who',
                'incorrect1' => 'he',
                'incorrect2' => 'what',
                'incorrect3' => 'that he',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'You look ________ in red!',
                'correct_answer' => 'very nice',
                'incorrect1' => 'nicely',
                'incorrect2' => 'too nice',
                'incorrect3' => 'most nicely',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'sd',
                'correct_answer' => '1',
                'incorrect1' => '2',
                'incorrect2' => '3',
                'incorrect3' => '4',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Can you use ________ computer?',
                'correct_answer' => 'a',
                'incorrect1' => 'one',
                'incorrect2' => 'two',
                'incorrect3' => 'an',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Under no circumstances ________ or exchanged.',
                'correct_answer' => 'can good be returned',
                'incorrect1' => 'goods should be returned',
                'incorrect2' => 'good will be returned',
                'incorrect3' => 'are goods being returned',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Frank ________ when he case lying on the floor',
                'correct_answer' => 'was about to leave',
                'incorrect1' => 'has about to leave',
                'incorrect2' => 'is about to leave',
                'incorrect3' => 'had about to leave',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'He ________ newspapers for ten years.',
                'correct_answer' => 'has been selling',
                'incorrect1' => 'is selling',
                'incorrect2' => 'sells',
                'incorrect3' => 'has been sold',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'This luggage is quite similar to ________.',
                'correct_answer' => 'that one',
                'incorrect1' => 'those',
                'incorrect2' => 'in additional',
                'incorrect3' => 'that',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'The doctor showed the new nurse ________ to do.',
                'correct_answer' => 'what',
                'incorrect1' => 'that',
                'incorrect2' => 'how',
                'incorrect3' => 'as',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'What does he ________ for a living?',
                'correct_answer' => 'do',
                'incorrect1' => 'does',
                'incorrect2' => 'make',
                'incorrect3' => 'makes',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'The murderer was ________ yesterday.',
                'correct_answer' => 'hung',
                'incorrect1' => 'hanging',
                'incorrect2' => 'hanged',
                'incorrect3' => 'hang',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'Dont let your brothers ________ the present.',
                'correct_answer' => 'see',
                'incorrect1' => 'seen',
                'incorrect2' => 'seeing',
                'incorrect3' => 'to see',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'No, thank you, I dont ________ sugar in tea.',
                'correct_answer' => 'put',
                'incorrect1' => 'eat',
                'incorrect2' => 'drink',
                'incorrect3' => 'take',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'My cousin ________ bank manager.',
                'correct_answer' => 'is a',
                'incorrect1' => 'makes',
                'incorrect2' => 'is',
                'incorrect3' => 'he is',
                'status' => '1',
            ],
            [
                'category_id' => '1',
                'question' => 'She is talking to you. Please listen to ________.',
                'correct_answer' => 'her',
                'incorrect1' => 'hers',
                'incorrect2' => 'she',
                'incorrect3' => 'him',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Trước khi chơi thể thao chúng ta cần làm gì?',
                'correct_answer' => 'Khởi động, làm nóng người',
                'incorrect1' => 'Để tự nhiên',
                'incorrect2' => 'Ngồi thả lỏng',
                'incorrect3' => 'Vào chơi luôn',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Môn thể thao nào được coi là môn thể thao "vua"?',
                'correct_answer' => 'Bóng đá',
                'incorrect1' => 'Cờ vua',
                'incorrect2' => 'Bóng chuyển',
                'incorrect3' => 'Cầu lông',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ nhận bao nhiêu thẻ vàng thì sẽ bằng với 1 thẻ đỏ',
                'correct_answer' => '2',
                'incorrect1' => '5',
                'incorrect2' => '6',
                'incorrect3' => '4',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Trên sân bóng đá có tối đa bao nhiêu cầu thủ',
                'correct_answer' => '22',
                'incorrect1' => '14',
                'incorrect2' => '12',
                'incorrect3' => '11',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ có biệt danh là Vua bóng đá',
                'correct_answer' => 'Pele',
                'incorrect1' => 'Cristiano Ronaldo',
                'incorrect2' => 'Diego Maradona',
                'incorrect3' => 'Ronaldinho',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Đội tuyển bóng đá có biệt danh "Cơn lốc màu da cam" là',
                'correct_answer' => 'Hà Lan',
                'incorrect1' => 'Hy Lạp',
                'incorrect2' => 'Đức',
                'incorrect3' => 'Tây Ban Nha',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Một trận đấu bóng đá chính thức sẽ kéo dài trong bao lâu?',
                'correct_answer' => '90 phút',
                'incorrect1' => '20 phút',
                'incorrect2' => '60 phút',
                'incorrect3' => '45 phút',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Việt Nam đã tham dự VCK World Cup bao nhiêu lần?',
                'correct_answer' => '0',
                'incorrect1' => '1',
                'incorrect2' => '2',
                'incorrect3' => '3',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Thủ môn được sử dụng tay tại vị trí nào trên sân?',
                'correct_answer' => 'Vòng cấm',
                'incorrect1' => 'Bất cứ vị trí nào',
                'incorrect2' => 'Vòng tròn giữa sân',
                'incorrect3' => 'Khi ném biên',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ ghi bàn nhiều nhất tại các kì World Cup',
                'correct_answer' => 'Miroslav Klose',
                'incorrect1' => 'Fernando Torres',
                'incorrect2' => 'Lionel Messi',
                'incorrect3' => 'Ronaldo de Lima',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ nhận giải Quả bóng vàng Việt Nam năm 2020 là',
                'correct_answer' => 'Nguyễn Văn Quyết',
                'incorrect1' => 'Nguyễn Trọng Hoàng',
                'incorrect2' => 'Nguyễn Quang Hải',
                'incorrect3' => 'Quế Ngọc Hải',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Đội tuyển quốc gia vô địch World Cup 2014 là',
                'correct_answer' => 'Đức',
                'incorrect1' => 'Pháp',
                'incorrect2' => 'Argentina',
                'incorrect3' => 'Tây Ban Nha',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ nhận giải thưởng FIFA The Best 2020 là',
                'correct_answer' => 'Robert Lewandowski',
                'incorrect1' => 'Cristiano Ronaldo',
                'incorrect2' => 'Neymar',
                'incorrect3' => 'Lionel Messi',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Thành tích của đội tuyển Việt Nam tại VCK U23 Châu Á 2018',
                'correct_answer' => 'Á quân',
                'incorrect1' => 'Vô địch',
                'incorrect2' => 'Hạng 3',
                'incorrect3' => 'Hạng 4',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'CLB vô địch Champions League 2020 là',
                'correct_answer' => 'Bayern Munich',
                'incorrect1' => 'Manchester United',
                'incorrect2' => 'Paris Saint Germain',
                'incorrect3' => 'Barcelona',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'U23 Việt Nam đã đánh bại ai tại chung kết SEA GAMES 2019',
                'correct_answer' => 'Indonesia',
                'incorrect1' => 'Thái Lan',
                'incorrect2' => 'Lào',
                'incorrect3' => 'Philipines',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ Việt Nam nào từng thi đấu cho CLB SC Heereveen',
                'correct_answer' => 'Đoàn Văn Hậu',
                'incorrect1' => 'Nguyễn Công Phượng',
                'incorrect2' => 'Lê Công Vinh',
                'incorrect3' => 'Lương Xuân Trường',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ Alphonso Davies mang quốc tịch gì',
                'correct_answer' => 'Canada',
                'incorrect1' => 'Liberia',
                'incorrect2' => 'Ghana',
                'incorrect3' => 'Pháp',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Đội chủ nhà của World Cup 1998 là',
                'correct_answer' => 'Pháp',
                'incorrect1' => 'Đức',
                'incorrect2' => 'Croatia',
                'incorrect3' => 'Brazil',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cristiano Ronaldo chưa từng thi đấu cho CLB nào sau đây',
                'correct_answer' => 'Benfica',
                'incorrect1' => 'Juventus',
                'incorrect2' => 'Manchester United',
                'incorrect3' => 'Real Madrid',
                'status' => '1',
            ], 
            [
                'category_id' => '2',
                'question' => 'CLB nào vô địch Ngoại Hạng Anh nhiều nhất?',
                'correct_answer' => 'Manchester United',
                'incorrect1' => 'Chelsea',
                'incorrect2' => 'Manchester City',
                'incorrect3' => 'Arsenal',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Đôi tuyển việt nam vô địch AFF CUP vào những năm nào ?',
                'correct_answer' => 'năm 2008, 2018',
                'incorrect1' => 'năm 2008, 2018, 2019',
                'incorrect2' => 'năm 2018, 2019',
                'incorrect3' => 'năm 2008, 2019',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ nào dưới đây thuộc biên chế clb Chelsea hiện nay ?',
                'correct_answer' => 'Trevoh Chalobah',
                'incorrect1' => 'Allan Saint-Maximin',
                'incorrect2' => 'Aleksey Miranchuk',
                'incorrect3' => 'Timothy Castagne',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Eduardo Camavinga đang thuộc biên chế clb nào ?',
                'correct_answer' => 'Real Madrid',
                'incorrect1' => 'Barcelona',
                'incorrect2' => 'Arsenal',
                'incorrect3' => 'Atlético de Madrid',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Vua phá lưới world cup 2018 là ai ?',
                'correct_answer' => 'Harry Kane',
                'incorrect1' => 'Mario Mandžukić',
                'incorrect2' => 'Cristiano Ronaldo',
                'incorrect3' => 'Neymar',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cầu thủ đắt giá nhất hiện nay là ai ?',
                'correct_answer' => 'Lukaku',
                'incorrect1' => 'Mbappe',
                'incorrect2' => 'Morata',
                'incorrect3' => 'Neymar',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Tiền đạo xuất sắc nhất lịch sử Brazil là ai ?',
                'correct_answer' => 'Pelé',
                'incorrect1' => 'Ronaldo de Lima',
                'incorrect2' => 'Rivaldo',
                'incorrect3' => 'Garrincha',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Chủ nhân của Ballon dOr 1988 là ai ?',
                'correct_answer' => 'Marco van Basten',
                'incorrect1' => 'Ruud Gullit',
                'incorrect2' => 'Frank Rijkaard',
                'incorrect3' => 'Harry Marguire',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Nhà vô địch Ngoại Hạng Anh năm 2008 là clb nào ?',
                'correct_answer' => 'Manchester United',
                'incorrect1' => 'Manchester City',
                'incorrect2' => 'Liverpool',
                'incorrect3' => 'Arsenal',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Hlv nào dưới đây từng dẫn dắt Manchester United ?',
                'correct_answer' => 'David Moyes',
                'incorrect1' => 'Zinédine Zidane',
                'incorrect2' => 'Filippo Inzaghi',
                'incorrect3' => 'Joachim Löw',
                'status' => '1',
            ],
            [
                'category_id' => '2',
                'question' => 'Cặp trung vệ hay nhất hiện nay',
                'correct_answer' => 'Leonardo Bonucci -Giorgio Chiellini',
                'incorrect1' => 'Marquinhos-Presnel Kimpembe',
                'incorrect2' => 'Virgil van Dijk -Joe Gomez',
                'incorrect3' => 'Ruben Dias -John Stones',
                'status' => '1',
            ],
            [
                'category_id' => '3',
                'question' => 'Công thức dùng để tính nồng độ phần trăm của dung dịch',
                'correct_answer' => 'C% = mct/mdd . 100%',
                'incorrect1' => 'C% = mdd/mct . 100%',
                'incorrect2' => 'CM = n/V',
                'incorrect3' => 'C% = mct/100% . mdd',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Phản ứng xảy ra khi nước tác dụng với oxit axit tạo thành dung dịch axit:',
                'correct_answer' => 'H2O + N2O5 -> HNO3',
                'incorrect1' => 'H2O + Ca -> Ca(OH)2 + H2',
                'incorrect2' => 'H2O + Na2O -> NaOH',
                'incorrect3' => 'H2O + SiO2 -> H2SiO3',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Dãy chất nào sau đây tác dụng được với O2?',
                'correct_answer' => 'SO2, Fe, S',
                'incorrect1' => 'CaO, Ca, Mg',
                'incorrect2' => 'Na2O, Na, Zn',
                'incorrect3' => 'BaO, P, H2',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Dãy chất sau đây tác dụng được với nước',
                'correct_answer' => 'Ba, Na2O, SO3',
                'incorrect1' => 'Li, ZnO, P2O5',
                'incorrect2' => 'Ca, K2O, SiO2',
                'incorrect3' => 'Al, Fe2O3,N2O5',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'ở nhiệt độ xác định, dung dịch bão hòa là',
                'correct_answer' => 'dung dịch không thể hòa tan chất tan',
                'incorrect1' => 'dung dịch có thể hòa tan thê chất tan',
                'incorrect2' => 'dung dịch chỉ hòa tan được chất lỏng trong chất lỏng',
                'incorrect3' => 'dung dịch chỉ hòa tan được chất rắn trong dung môi',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Khi giảm nhiệt độ và tăng áp suất thì độ tan của chất khí trong nước:',
                'correct_answer' => 'tăng',
                'incorrect1' => 'có thể tăng và có thể giảm',
                'incorrect2' => 'không tăng và cũng không giảm',
                'incorrect3' => 'giảm',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Dãy chất nào sau đây là axit:',
                'correct_answer' => 'HBr, HNO3, H2SO3, H3PO4',
                'incorrect1' => 'HCl, NaOH, Fe2(SO4)3, H2SO4',
                'incorrect2' => 'Ca(OH)2, LiOH, NaOH, Al(OH)3',
                'incorrect3' => 'Ba(H2PO4)2, Na2SO4, ZnCl2, KHCO3',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Hòa tan 150 ml rượu etylic (cồn) vào 100ml nước cất thu được dung dịch rượu',
                'correct_answer' => 'chất tan là nước, dung môi là rượu etylic',
                'incorrect1' => 'cả hai chất vừa là chất tan, vừa là dung môi',
                'incorrect2' => 'nước hoặc rượu có thể là chất tan hoặc dung môi',
                'incorrect3' => 'chất tan là rượu etylic, dung môi là nước',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Khối lượng chất tan cần dùng để pha chế 40 gam dung dịch MgCl2 có nồng độ 6%',
                'correct_answer' => '2,4g',
                'incorrect1' => '666,6g',
                'incorrect2' => '0,416g',
                'incorrect3' => '15g',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Hầu hết các chất rắn, độ tan trong nước tăng khi nhiệt độ',
                'correct_answer' => 'tăng',
                'incorrect1' => 'có thể tăng và có thể giảm',
                'incorrect2' => 'giảm',
                'incorrect3' => 'không tan cũng không giảm',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Dãy chất là muối trung hòa:',
                'correct_answer' => 'CaCl2, Fe2(SO4)3, ZnS, Na2CO3',
                'incorrect1' => 'Ba(H2PO4)2, Na2SO4, ZnCl2, KHCO3',
                'incorrect2' => 'Ca(OH)2, Al(OH)3, NaOH, Mg(OH)2',
                'incorrect3' => 'H2CO3, H2S, H3PO4, HNO3',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Công thức dùng để tính số mol chất tan khi biết nồng độ mol là:',
                'correct_answer' => 'n = CM.V',
                'incorrect1' => 'n = V/22,4',
                'incorrect2' => 'n = m/M ',
                'incorrect3' => 'n = CM/V',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'hòa tan 20 gam muối ăn NaCl vào 60 gam nước. Nồng độ phần trăm của dung dịch là:',
                'correct_answer' => '25%',
                'incorrect1' => '30%',
                'incorrect2' => '20%',
                'incorrect3' => '15%',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Dung dịch là hỗn hợp:',
                'correct_answer' => 'đồng nhất của chất tan và dung môi',
                'incorrect1' => 'Của chất rắn, chất lỏng và chất khí trong dung môi',
                'incorrect2' => 'Của chất khí trong chất lỏng',
                'incorrect3' => 'Của chất rắn trong chất lỏng',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Dãy chất nào sau đây là Bazơ',
                'correct_answer' => 'Ca(OH)2, LiOH, NaOH, Al(OH)3',
                'incorrect1' => 'Ba(H2PO4)2, Na2SO4, ZnCl2, KHCO3',
                'incorrect2' => 'HBr, HNO3, H2SO3, H3PO4',
                'incorrect3' => 'HCl, NaOH, Fe2(So4)3, H2SO4',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Hầu hết các chất rắn, độ tan trong nước giảm khi nhiệt độ:',
                'correct_answer' => 'giảm',
                'incorrect1' => 'không tan và cũng không giảm',
                'incorrect2' => 'có thể tăng và có thể giảm',
                'incorrect3' => 'tăng',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Trộn 10ml dầu ăn vào 20ml nước ( ở nhiệt độ phòng), thu được:',
                'correct_answer' => 'hỗn hợp dầu văn với nước',
                'incorrect1' => 'dung dịch chưa bão hòa',
                'incorrect2' => 'dung dịch bão hòa',
                'incorrect3' => 'dung dịch nước dầu ăn',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Dãy chất sau đây tác dụng được với nước (ở điều kiện thường)',
                'correct_answer' => 'Na2O, K, SO3',
                'incorrect1' => 'Ca, Al, Cu',
                'incorrect2' => 'S, P, N2',
                'incorrect3' => 'K2O, Fe2O3, SiO2',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Ở nhiệt độ xác định, dung dịch chưa bão hòa là',
                'correct_answer' => 'dung dịch có thể hòa tan thêm chất tan',
                'incorrect1' => 'dung dịch không thể hòa tan thêm chất tan',
                'incorrect2' => 'dung dịch chỉ hòa tan được chất lỏng trong chất lỏng',
                'incorrect3' => 'dung dịch chỉ hòa tan được chất rắn trong dung môi',
                'status' => '1',
            ], 
            [
                'category_id' => '3',
                'question' => 'Công thức dùng để tính nồng độ mol của dung dịch:',
                'correct_answer' => 'CM = n/V',
                'incorrect1' => 'CM = n.V',
                'incorrect2' => 'CM = V/n',
                'incorrect3' => 'n = CM.V',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Hệ điều hành thuộc loại phần mềm nào?',
                'correct_answer' => 'Phần mềm hệ thống',
                'incorrect1' => 'Phần mềm kế toán',
                'incorrect2' => 'Phần mềm ứng dụng',
                'incorrect3' => 'Phần mềm diệt vi rút',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Phương án nào sau đây không đảm bảo an toàn khi sử dụng mật khẩu?',
                'correct_answer' => 'Dùng một mật khẩu duy nhất cho nhiều trang web khác nhau',
                'incorrect1' => 'Tạo mật khẩu có độ dài ít nhất 8 ký tự bao gồm chữ cái, chữ số, kí tự đặc biệt',
                'incorrect2' => 'Tạo mật khẩu dễ nhớ đối với bạn nhưng khó đoán đối với người khác',
                'incorrect3' => 'Không bao giờ tiết lộ mật khẩu của bạn cho bất kỳ ai',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Trong các phương tiện sau, đâu là phương tiện truyền dẫn không dây?',
                'correct_answer' => 'Sóng truyền qua vệ tinh',
                'incorrect1' => 'Cáp đồng trục',
                'incorrect2' => 'Cáp quang',
                'incorrect3' => 'Cáp xoắn đôi',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Thông tin khi đưa vào máy tính, chúng đều được biến đổi thành dạng chung đó là?',
                'correct_answer' => 'Dãy bít',
                'incorrect1' => 'Hình ảnh',
                'incorrect2' => 'Văn bản',
                'incorrect3' => 'Âm thanh',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Đơn vị nào không dùng để đo dung lượng bộ nhớ trong?',
                'correct_answer' => 'Megahertz',
                'incorrect1' => 'Kilobyte',
                'incorrect2' => 'Megabyte',
                'incorrect3' => 'Gigabyte',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Trong các loại phần mềm sau, phần mềm nào thuộc phần mềm hệ thống?',
                'correct_answer' => 'Phần mềm TurboPascal',
                'incorrect1' => 'Phần mềm duyệt web',
                'incorrect2' => 'Hệ điều hành',
                'incorrect3' => 'Phần mềm Microsoft Office',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Email là gì?',
                'correct_answer' => 'Thư điện tử',
                'incorrect1' => 'Instagram',
                'incorrect2' => 'Twitter',
                'incorrect3' => 'Games online',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Công dụng của Email là gì?',
                'correct_answer' => 'Gửi và nhận thư qua mạng máy tính',
                'incorrect1' => 'Diệt virus máy tính',
                'incorrect2' => 'Chơi game giải trí',
                'incorrect3' => 'Trình duyệt web',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Phần mềm nào sau đây không phải là phần mềm hệ thống?',
                'correct_answer' => 'TeamViewer',
                'incorrect1' => 'Windows 7',
                'incorrect2' => 'Linux',
                'incorrect3' => 'Windows Xp',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Trong Tin học, tệp (tập tin) là khái niệm chỉ?',
                'correct_answer' => 'Một đơn vị lưu trữ thông tin trên bộ nhớ ngoài',
                'incorrect1' => 'Một trang Web',
                'incorrect2' => 'Một văn bản',
                'incorrect3' => 'Một gói tin',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Phần mềm nào sau đây dùng để xử lý văn bản?',
                'correct_answer' => 'Microsoft Word',
                'incorrect1' => 'Microsoft Excel',
                'incorrect2' => 'Microsoft PowerPoint',
                'incorrect3' => 'Microsoft Access',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Người sử dụng có thể giao tiếp với máy tính bằng cách nào trong các cách sau đây?',
                'correct_answer' => 'Đưa vào các lệnh (Command) hoặc chọn trên bảng chọn (Menu)',
                'incorrect1' => 'Chỉ bằng "giọng nói"',
                'incorrect2' => 'Chỉ bằng dòng lệnh (Command.)',
                'incorrect3' => 'Chỉ bằng hệ thống bảng chọn (Menu)',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Virus máy tính là gì?',
                'correct_answer' => 'Chương trình máy tính có khả năng tự lây lan',
                'incorrect1' => 'Virus sinh học lây lan qua việc sử dụng chung bàn phím',
                'incorrect2' => 'Chương trình hỗ trợ tìm kiếm thông tin trên mạng Internet',
                'incorrect3' => 'Chương trình máy tính mô tả hoạt động của virus',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Mozilla Firefox là phần mềm gì?',
                'correct_answer' => 'Trình duyệt web',
                'incorrect1' => 'Phần mềm trò chơi',
                'incorrect2' => 'Phần mềm biên tập ảnh',
                'incorrect3' => 'Phần mềm trình chiếu',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Phần mềm Photoshop dùng để làm gì?',
                'correct_answer' => 'Chỉnh sửa và biên tập ảnh',
                'incorrect1' => 'Cắt ghép video',
                'incorrect2' => 'Trò chơi máy tính',
                'incorrect3' => 'Quản trị cơ sở dữ liệu',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'phần cứng của một hệ thống máy tính bao gồm?',
                'correct_answer' => 'Máy tính và các thiết bị vật lí liên quan',
                'incorrect1' => 'Bộ xử lí trung tâm(CPU)',
                'incorrect2' => 'Bộ nhớ ngoài(Đĩa CD,Ổ đĩa cứng..)',
                'incorrect3' => 'Bộ nhớ trong(RAM,ROM)',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Hãy chỉ ra tên của thiết bị mạng?',
                'correct_answer' => 'Modem',
                'incorrect1' => 'Printer',
                'incorrect2' => 'Webcam',
                'incorrect3' => 'USB',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Chọn khẳng định đúng, khả năng xử lý của máy tính phụ thuộc vào?',
                'correct_answer' => 'Tốc độ CPU, dung lượng bộ nhớ RAM, dung lượng và tốc độ ổ cứng',
                'incorrect1' => 'Dung lượng bộ nhớ ngoài',
                'incorrect2' => 'Tốc độ quay quạt chíp',
                'incorrect3' => 'Dung lượng bộ nhớ trong',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Mạng xã hội bao gồm?',
                'correct_answer' => 'Facebook, Twitter, Instagram, Tumblr',
                'incorrect1' => 'Hộp thư điện tử',
                'incorrect2' => 'GoogleChorm, Mozilla Firefox',
                'incorrect3' => 'Dịch vụ chuyển phát nhanh',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Hệ nhị phân dùng mấy ký tự để biểu diễn các số?',
                'correct_answer' => '2',
                'incorrect1' => '10',
                'incorrect2' => '8',
                'incorrect3' => '16',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Chọn khẳng định đúng, bản quyền là?',
                'correct_answer' => 'Quyền tác giả',
                'incorrect1' => 'Quyền được sao chép',
                'incorrect2' => 'Quyền được công bố',
                'incorrect3' => 'Quyền được mua bán',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Chức năng chính của thương mại điện tử dùng để?',
                'correct_answer' => 'Mua bán qua mạng',
                'incorrect1' => 'Gửi tệp tin đính kèm',
                'incorrect2' => 'Quản lý tiền trực tuyến',
                'incorrect3' => 'Nhận thư điện tử',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Để quản lý tệp và thư mục ta dùng chương trình nào?',
                'correct_answer' => 'Windows Explorer',
                'incorrect1' => 'Internet Explorer',
                'incorrect2' => 'Microsoft Excel',
                'incorrect3' => 'Microsoft Word',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Mật khẩu nào sau đây là khó phá nhất đối với 1 hacker?',
                'correct_answer' => 'p@ssWord123',
                'incorrect1' => 'password',
                'incorrect2' => '123456',
                'incorrect3' => 'abcd1234',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Người dùng và máy tính giao tiếp với nhau thông qua?',
                'correct_answer' => 'Hệ điều hành',
                'incorrect1' => 'Modem',
                'incorrect2' => 'RAM',
                'incorrect3' => 'Loa và màn hình',
                'status' => '1',
            ], 
            [
                'category_id' => '4',
                'question' => 'Máy tính đọc dữ liệu nhanh nhất từ đâu?',
                'correct_answer' => 'Đĩa cứng',
                'incorrect1' => 'Đĩa mềm',
                'incorrect2' => 'USB',
                'incorrect3' => 'Internet',
                'status' => '1',
            ], 
        ]);
    }
}
